services:
  - type: web
    name: yclients-proxy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PROXY_SECRET
        value: vdohvydoh2026
